on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      # sam build 
      # - run: sam build --use-container

      # Run Unit tests- Specify unit tests here
      - name: Unit testing
        run: |
          npm i
          npm run test

      - name: Build layer zip file
        run: |
          npm run build
          zip -r ./tbk-layer.zip nodejs

      - name: Create S3 Bucket to store layer code (if not already exists)
        run: |
          aws s3api head-bucket --bucket jooycar-payment-handlers-bkt 2>/dev/null || aws s3 mb s3://jooycar-payment-handlers-bkt

      # - name: Upload Layer Code
      #   run: aws s3api put-object --bucket jooycar-payment-handlers-bkt --key dir-1/my_images.tar.bz2 --body my_images.tar.bz2

      # - run: |
      #     sam deploy \
      #     --no-confirm-changeset \
      #     --no-fail-on-empty-changeset \
      #     --stack-name sam-hello-world \
      #     --s3-bucket payment-handlers-bkt \
      #     --capabilities CAPABILITY_IAM \
      #     --region us-east-1 