on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: Configure variables
        shell: bash
        id: vars
        run: |
          # Set variables
          BUCKET_NAME=jooycar-payment-handlers-bkt
          LAYER_FILE_KEY=tbk-layer.zip
          BRANCH=${GITHUB_REF##*/}
          # In this step we are setting variables and persistenting them
          # into the environment so that they can be utilized in other steps
          echo "::set-output name=bucket_name::$BUCKET_NAME"
          echo "::set-output name=layer_file_key::$LAYER_FILE_KEY"
          echo "::set-output name=branch::$BRANCH"
          # Output variables to ensure their values are set correctly when ran
          echo "The layer_file_key is $LAYER_FILE_KEY"
          echo "The bucket_name is $BUCKET_NAME"
      # sam build 
      - run: echo "${{ steps.vars.outputs.branch }}"

      # Run Unit tests- Specify unit tests here
      - name: Unit testing
        run: |
          npm i
          npm run test

      - name: Build layer zip file
        run: |
          npm run build
          zip -r ./${{ steps.vars.outputs.bucket_name }} nodejs

      - name: List layer zip file
        run: |
          ls -la
          pwd

      - name: Create S3 Bucket to store layer code (if not already exists)
        run: |
          aws s3api head-bucket --bucket ${{ steps.vars.outputs.bucket_name }} 2>/dev/null || aws s3 mb s3://${{ steps.vars.outputs.bucket_name }}

      - name: Upload Layer Code
        run: aws s3api put-object --bucket ${{ steps.vars.outputs.bucket_name }} --key ${{ steps.vars.outputs.branch }}/${{ steps.vars.outputs.layer_file_key }} --body ${{ steps.vars.outputs.layer_file_key }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyStack
          template: IaC/stack.yaml
          parameter-overrides: "LayerBucket=${{ steps.vars.outputs.bucket_name }},LayerFileKey=${{ steps.vars.outputs.branch }}/${{ steps.vars.outputs.layer_file_key }}"
